### ISSUE TITLE
No output from [puts]

### ISSUE THREAD

**Issue by arjenmarkus** [tcllab/tclmake#3]
While trying to sort out the problem described in ticket #2 I tried a [puts] of all the files in the working directory but got no output at all. Not even when I wrote the output of the [glob] command to a file:
`
hello.f90:	d:/tcl-programs/tclmake/testje/aa
	puts [glob *]
	set outfile [open report w]
	puts $outfile
	close $outfile         
`
There is no file "report" to be found.

**Comment by tcllab** [comment]
If the file hello.f90 is newer than d:/tcl-programs/tclmake/testje/aa, then the Tcl code associated with the rule won't run.

You can use the command-line option --update to force a target's Tcl code to run even if the target is not out of date.

**Comment by arjenmarkus** [comment]
Yes, from my experiments I deduce that the rule for "updating" "hello.f90" by means of the file "aa" was not triggered, even though "aa" was newer than "hello.f90". However, with the new version it is only triggered if I leave out the absolute path. It is when I use the relative path "./" or leave it out completely - relative paths seem to do it. 

Hm, if I leave out the "D:" drive indicator it works as well - that is of course a Windows-specific path, but still.

Also: --update seems to have no effect - the program is not rebuilt.

**Comment by arjenmarkus** [comment]
Oh, could it be that the colon in "D:/tcl-programs/tclmake/testje/aa" gets in the way of identifying the proper dependencies?

**Comment by tcllab** [comment]
Yes, that is what's happening.

Note that you can get more insight into what is happening by using the --debug command line flag.

I created a makefile.tmk containing:

```
hello.f90: D:/tcl-programs/tclmake/testje/aa
	@puts "target:$@ prereq:$<"
```

and ran it with the --debug flag.  It reports the rule as a "Pattern rule with explicit targets" of the form "hello.f90 : D : /tcl-programs/tclmake/testje/aa"

Since the pattern-matching code can't make sense of this form, no prereqs are generated, hello.f90 is not marked out of date and the update script is not run.

I just added a kludge to the code that allows a Windows user to use a "|" in place of a ":" in a target or prereq name.  This allowed me to create a new makefile.tmk containing:

```
hello.f90: D|/tcl-programs/tclmake/testje/aa
	@puts "target:$@ prereq:$<"
	
D|/tcl-programs/tclmake/testje/aa:
	@puts target:$@
```

and the scripts are executed as expected.  Note the automatic variables contain the proper filenames complete with colon.

Please let me know if this works for you.
